Algoritmo "sequencia_impares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/01/2024
Var


   x, i : inteiro


Inicio

   escreva("Digite o valor de X: ")
   leia(x)
   
   para i de 1 ate x faca
      se i % 2 <> 0 entao
       escreval(i)
      fimse
   fimpara

Fimalgoritmo